### ISSUE TITLE
Make the local version work fully offline!

### ISSUE THREAD

**Issue by Naereen** [algorithm-visualizer/algorithm-visualizer#234]
Hi!
I love this project, it's awesome!
I successfully ran the project locally, but what a disappointment when I saw that unpkg.com is used a lot in some scripts!
It should run *locally*, like really locally, without an Internet connection!
I wanted to use this project in classes I teach, and I cannot rely on it if it needs Internet access.

Do you have any idea how I can easily change `src/backend/tracers/js/worker.js` to not load the scripts from https://unpkg.com/algorithm-visualizer@latest/dist/algorithm-visualizer.js and https://unpkg.com/babel-standalone@6/babel.min.js but from the node_modules where they should already be installed?

Thanks in advance :clap:!

**Comment by Naereen** [comment]
I tried to download the two files and copy them in the `src/backend/tracers/js/` folder, and changed the two `importScripts('https://unpkg.com/....')` lines to simply `importScripts('file.js')` but it fails.

**Comment by parkjs814** [comment]
Hi @Naereen, glad you are considering using it in your classes.

Since [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) is downloaded from the server and runs locally on browsers, you cannot use `importScripts` with relative paths. One way to run offline is to copy two script files under `/src/frontend/static`. Then, you can import those scripts which are served on `http://localhost:8080/[script].js`.

Considering not many users running it locally without an Internet connection, I decided to use [unpkg.com](https://unpkg.com/) to reduce traffic serving `babel.min.js` (~200KB). Actually, I am thinking of not using `babel` anymore as almost all modern browsers support ES6. In that case, I will definitely consider making it run fully locally.
